#vim :
sudo: required

language:
 - c

compiler:
  - gcc

install:
 - wget -q -O- https://raw.githubusercontent.com/mithro/travis-trusty/master/setup.sh | bash
 - chmod a+rx $PWD/.travis-*.sh
 - /trusty/run.py $PWD/.travis-setup.sh

script:
 - /trusty/run.py $PWD/.travis-run.sh

notifications:
  email:
    - hdmi2usb-spam@googlegroups.com
  irc: "irc.freenode.org#hdmi2usb"
