sudo: required

language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
  matrix:
   # Base targets
   - C=lm32 P=arty         T="base net"
   - C=lm32 P=atlys        T="base net"
   - C=lm32 P=mimasv2      T="base"
   - C=lm32 P=minispartan6 T="base"
   - C=lm32 P=netv2        T="base"
   - C=lm32 P=nexys_video  T="base net"
   - C=lm32 P=opsis        T="base net"
   - C=lm32 P=pipistrello  T="base"
   # Video targets
   - C=lm32 P=atlys        T="video"
   - C=lm32 P=netv2        T="video"
   - C=lm32 P=nexys_video  T="video"
   - C=lm32 P=opsis        T="video"
   # HDMI2USB targets
   - C=lm32 P=atlys        T="hdmi2usb"
   - C=lm32 P=opsis        T="hdmi2usb"
   # Only compile or1k for some platforms
   - C=or1k P=arty         T="base net"
   - C=or1k P=atlys        T="base net"
   - C=or1k P=opsis        T="base net"
#   - PLATFORM=sim

matrix:
  allow_failures:
   # These builds need fixing
   - env: C=lm32 P=pipistrello  T="base"
   # The HDMI2USB targets sometimes timeout
   - env: C=lm32 P=opsis        T="hdmi2usb"
   - env: C=lm32 P=atlys        T="hdmi2usb"
   # or1k on mimasv2 occasionally fails
   - env: C=or1k P=mimasv2      T="base"
  fast_finish: true

install:
 - export CPU="$C"
 - export PLATFORMS="$P"
 - export TARGETS="$T"
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
