sudo: required

language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
  matrix:
#   - PLATFORM=arty
   - PLATFORM=atlys SKIP_TARGETS="hdmi2usb\|video.*"
   - PLATFORM=atlys TARGET=video
   - PLATFORM=atlys TARGET=hdmi2usb
   - PLATFORM=minispartan6
#   - PLATFORM=netv2
#   - PLATFORM=nexys_video
#   - PLATFORM=pipistrello
   - PLATFORM=opsis SKIP_TARGETS="hdmi2usb\|video.*"
   - PLATFORM=opsis TARGET=video
   - PLATFORM=opsis TARGET=hdmi2usb
#   - PLATFORM=sim
   # Test multiple CPU archs on the mimasv2
   - CPU=lm32 PLATFORM=mimasv2
   - CPU=or1k PLATFORM=mimasv2

install:
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
