sudo: required

language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - realpath
    - build-essential
    - gnupg
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - fxload

env:
  matrix:
   - BOARD=atlys TARGET=base
   - BOARD=atlys TARGET=hdmi2usb
   - BOARD=atlys TARGET=hdmi2eth
   - BOARD=opsis TARGET=base
   - BOARD=opsis TARGET=hdmi2usb

install:
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/run.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
   - "chat.freenode.net#timvideos"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
