sudo: required

language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
  matrix:
   - CPU=lm32 PLATFORM=arty TARGETS="base net"
   - CPU=or1k PLATFORM=arty TARGETS="base net"
   - CPU=lm32 PLATFORM=atlys SKIP_TARGETS="hdmi2usb\|video.*"
   - CPU=or1k PLATFORM=atlys TARGETS="base net"
   - PLATFORM=atlys TARGET=video
   - PLATFORM=atlys TARGET=hdmi2usb
   - PLATFORM=minispartan6
   - PLATFORM=netv2 TARGETS="base video"
   - PLATFORM=nexys_video TARGETS="base net video"
#   - PLATFORM=pipistrello
   - CPU=lm32 PLATFORM=opsis SKIP_TARGETS="hdmi2usb\|video.*\|memtest"
   - CPU=or1k PLATFORM=opsis TARGETS="base net"
   - PLATFORM=opsis TARGET=video
   - PLATFORM=opsis TARGET=hdmi2usb
#   - PLATFORM=sim
   - CPU=lm32 PLATFORM=mimasv2 TARGETS="base"
   - CPU=or1k PLATFORM=mimasv2 TARGETS="base" # or1k and memtest don't fit on mimasv2

matrix:
  allow_failures:
   # or1k on mimasv2 occasionally fails
   - env: CPU=or1k PLATFORM=mimasv2 TARGETS="base"
   # The HDMI2USB targets sometimes timeout
   - env: PLATFORM=opsis TARGET=hdmi2usb
   - env: PLATFORM=atlys TARGET=hdmi2usb
  fast_finish: true

install:
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
